name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.x
        cache: true

    - name: Download dependencies
      run: go mod download

    - name: Lint
      run: make lint

    - name: Test
      run: make test
      # run: make cover

    # - name: Upload coverage
    #   uses: codecov/codecov-action@v3
